# Build Stage
FROM node:20-alpine AS builder
WORKDIR /app

# Nur die package-Dateien zuerst kopieren (Cache für npm install)
COPY conduit-frontend/package*.json ./
RUN npm ci

# Dann den ganzen Frontend-Code kopieren
COPY conduit-frontend/ .

RUN npm run build --prod

# Serve Stage
FROM nginx:alpine
COPY --from=builder /app/dist/angular-conduit /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
