FROM python:3.6-slim AS build

WORKDIR /app

# requirements.txt vom backend-Ordner ins Image kopieren
COPY conduit-backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Rest vom Backend-Code ins Image kopieren
COPY conduit-backend/ .

# entrypoint.sh aus dem Hauptverzeichnis ins Image kopieren
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 8000
ENTRYPOINT ["/app/entrypoint.sh"]