FROM python:3.6-slim AS build

WORKDIR /app

# requirements.txt vom backend-Ordner ins Image kopieren
COPY conduit-backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Rest vom Backend-Code ins Image kopieren
COPY conduit-backend/ .

EXPOSE 8000
CMD ["gunicorn", "conduit.wsgi:application", "--bind", "0.0.0.0:8000"]
