# Build Stage
FROM node:20-alpine AS builder
WORKDIR /app

# Copy only the package files first (cache for npm install)
COPY conduit-frontend/package*.json ./
RUN npm ci

# Then copy all the frontend code
COPY conduit-frontend/ .

RUN npm run build --prod

# Serve Stage
FROM nginx:alpine
COPY --from=builder /app/dist/angular-conduit /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
