# Build Stage
FROM node:18-alpine AS build
WORKDIR /app

# Nur die package-Dateien zuerst kopieren (Cache für npm install)
COPY conduit-frontend/package*.json ./
RUN npm install

# Dann den ganzen Frontend-Code kopieren
COPY conduit-frontend/ .

RUN npm run build

# Serve Stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
